simplify example to fetch user/org ID from ocm
bf2fc6cc711aee1a0c2a/kas-installer pull request #225
Opened 2022-09-22 12:13 UTC by jbpratt

simplify the incantation for fetching the user id and org id from ocm token

2022-09-22 12:31 UTC, machi1990 requested changes
added suggestions to add missing closing paretheses

2022-09-22 12:32 UTC, jbpratt commented
thanks for catching that @machi1990 :)

2022-09-22 15:59 UTC, MikeEdgar commented on kas-installer-defaults.env
> +# Owning users RH account_id. See `str=$(ocm token --payload | jq -r .account_id)`
I think you can even go a step further and remove the `str=$(` and `)`. The `str` variable was only present to support the bash substring that isn't present anymore.

2022-09-23 00:30 UTC, MikeEdgar approved these changes
lgtm :+1:

2022-09-23 08:03 UTC, merged